// Auto-generated by scripts/generate-pfp-assets.js.
// Do not edit this file manually.

export const PFP_ASSETS = [
  require("../../assets/pfp/1.jpeg"),
  require("../../assets/pfp/2.jpeg"),
  require("../../assets/pfp/3.jpeg"),
  require("../../assets/pfp/4.jpeg"),
  require("../../assets/pfp/5.jpeg"),
  require("../../assets/pfp/6.jpeg"),
  require("../../assets/pfp/7.jpeg"),
  require("../../assets/pfp/8.jpeg"),
  require("../../assets/pfp/9.jpeg"),
  require("../../assets/pfp/10.jpeg"),
  require("../../assets/pfp/11.jpeg"),
  require("../../assets/pfp/12.jpeg"),
  require("../../assets/pfp/13.jpeg"),
  require("../../assets/pfp/14.jpeg"),
  require("../../assets/pfp/15.jpeg"),
  require("../../assets/pfp/16.jpeg"),
  require("../../assets/pfp/17.jpeg"),
  require("../../assets/pfp/18.jpeg"),
  require("../../assets/pfp/19.jpeg"),
  require("../../assets/pfp/20.jpeg"),
  require("../../assets/pfp/21.jpeg"),
] as const;

export function getRandomPfpAsset() {
  return PFP_ASSETS[Math.floor(Math.random() * PFP_ASSETS.length)];
}
